const LS_KEY = (tripId) => `ferias_invite_${tripId}`

/** Returns the invite key for a trip, generating and saving one if it doesn't exist yet. */
export function getOrCreateInviteKey(tripId) {
  if (!tripId) return ''
  try {
    const existing = localStorage.getItem(LS_KEY(tripId))
    if (existing) return existing
    const key = Array.from(crypto.getRandomValues(new Uint8Array(6)))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('')
    try { localStorage.setItem(LS_KEY(tripId), key) } catch { /* quota — key will be regenerated next time */ }
    return key
  } catch { return '' }
}

/** Returns existing invite key or empty string (does NOT generate). */
export function getInviteKey(tripId) {
  if (!tripId) return ''
  try { return localStorage.getItem(LS_KEY(tripId)) || '' } catch { return '' }
}

/** Builds the full shareable URL including key. Uses current origin (works in any env). */
export function buildInviteUrl(tripId) {
  const key = getOrCreateInviteKey(tripId)
  return `${window.location.origin}/?trip=${tripId}&key=${key}`
}

/**
 * Returns the effective token for API write calls.
 * Owner path: stored in localStorage (generated by them).
 * Guest path: comes from the ?key= URL param.
 */
export function getEffectiveToken(tripId) {
  const local = getInviteKey(tripId)
  if (local) return local
  try {
    return new URLSearchParams(window.location.search).get('key') || ''
  } catch { return '' }
}
